# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS ${catalog_name}.ecom_gold.customer_cohort_analysis (
# MAGIC   cohort_month              DATE,      -- The month the user made their first purchase
# MAGIC   cohort_category           STRING,    -- Category of the user's first purchase
# MAGIC   cohort_brand              STRING,    -- Brand of the user's first purchase
# MAGIC   activity_month            DATE,      -- The month the user was active (made a purchase)
# MAGIC   month_number              BIGINT,    -- Months since cohort_month (0, 1, 2, ...)
# MAGIC   retained_users            BIGINT,    -- Number of users from this cohort active in this activity_month
# MAGIC   cohort_size               BIGINT,    -- Total number of users in this cohort
# MAGIC   total_revenue_from_cohort DOUBLE, -- Total revenue generated by this cohort in this activity_month
# MAGIC   total_purchases_from_cohort BIGINT -- Total purchases (events) by this cohort in this activity_month
# MAGIC )
# MAGIC CLUSTER BY(cohort_month, cohort_category, cohort_brand, activity_month);
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT OVERWRITE TABLE ${catalog_name}.ecom_gold.customer_cohort_analysis
# MAGIC
# MAGIC
# MAGIC WITH user_first_purchase AS (
# MAGIC   -- Step 1: Find the first purchase event for each user, including category and brand
# MAGIC   SELECT
# MAGIC     user_id,
# MAGIC     MIN(event_time) AS first_purchase_time -- Get the exact time to find the specific event
# MAGIC   FROM
# MAGIC     ${catalog_name}.ecom_silver.marketplace_events_silver
# MAGIC   WHERE
# MAGIC     event_type = 'purchase'
# MAGIC   GROUP BY
# MAGIC     user_id
# MAGIC ),
# MAGIC user_first_purchase_details AS (
# MAGIC   -- Step 2: Get the details (category, brand) of that very first purchase event
# MAGIC   SELECT
# MAGIC     ufp.user_id,
# MAGIC     CAST(ufp.first_purchase_time AS DATE) AS first_purchase_date,
# MAGIC     DATE_TRUNC('month', ufp.first_purchase_time) AS cohort_month,
# MAGIC     -- Get category and brand from the specific first purchase event
# MAGIC     FIRST_VALUE(s.category_L1) OVER (PARTITION BY ufp.user_id ORDER BY s.event_time ASC) AS cohort_category,
# MAGIC     FIRST_VALUE(s.brand) OVER (PARTITION BY ufp.user_id ORDER BY s.event_time ASC) AS cohort_brand
# MAGIC   FROM
# MAGIC     user_first_purchase ufp
# MAGIC   JOIN
# MAGIC     ${catalog_name}.ecom_silver.marketplace_events_silver s
# MAGIC     ON ufp.user_id = s.user_id AND ufp.first_purchase_time = s.event_time
# MAGIC   WHERE
# MAGIC     s.event_type = 'purchase' -- Ensure it's a purchase event
# MAGIC ),
# MAGIC user_monthly_activity AS (
# MAGIC   -- Step 3: Identify each month a user made a purchase and their revenue/purchases
# MAGIC   SELECT
# MAGIC     user_id,
# MAGIC     DATE_TRUNC('month', event_time) AS activity_month,
# MAGIC     SUM(price) AS monthly_revenue,
# MAGIC     COUNT(event_type) AS monthly_purchases -- Count of individual purchase events
# MAGIC   FROM
# MAGIC     ${catalog_name}.ecom_silver.marketplace_events_silver
# MAGIC   WHERE
# MAGIC     event_type = 'purchase'
# MAGIC   GROUP BY
# MAGIC     user_id,
# MAGIC     activity_month
# MAGIC ),
# MAGIC cohort_activity AS (
# MAGIC   -- Step 4: Join first purchase details with all activity months
# MAGIC   SELECT
# MAGIC     ufpd.user_id,
# MAGIC     ufpd.cohort_month,
# MAGIC     ufpd.cohort_category,
# MAGIC     ufpd.cohort_brand,
# MAGIC     uma.activity_month,
# MAGIC     -- Calculate month number (0 for cohort month, 1 for next month, etc.)
# MAGIC     MONTHS_BETWEEN(uma.activity_month, ufpd.cohort_month) AS month_number,
# MAGIC     uma.monthly_revenue,
# MAGIC     uma.monthly_purchases
# MAGIC   FROM
# MAGIC     user_first_purchase_details ufpd
# MAGIC   JOIN
# MAGIC     user_monthly_activity uma ON ufpd.user_id = uma.user_id
# MAGIC   WHERE
# MAGIC     uma.activity_month >= ufpd.cohort_month -- Ensure activity is not before cohort month
# MAGIC ),
# MAGIC cohort_summary AS (
# MAGIC   -- Step 5: Aggregate to get retained users, and total revenue/purchases per cohort_month, category, brand and month_number
# MAGIC   SELECT
# MAGIC     cohort_month,
# MAGIC     cohort_category,
# MAGIC     cohort_brand,
# MAGIC     activity_month,
# MAGIC     CAST(month_number AS BIGINT) AS month_number,
# MAGIC     COUNT(DISTINCT user_id) AS retained_users,
# MAGIC     SUM(monthly_revenue) AS total_revenue_from_cohort,
# MAGIC     SUM(monthly_purchases) AS total_purchases_from_cohort
# MAGIC   FROM
# MAGIC     cohort_activity
# MAGIC   GROUP BY
# MAGIC     cohort_month,
# MAGIC     cohort_category,
# MAGIC     cohort_brand,
# MAGIC     activity_month,
# MAGIC     month_number
# MAGIC ),
# MAGIC cohort_sizes AS (
# MAGIC   -- Step 6: Calculate the initial size of each cohort (by month, category, and brand)
# MAGIC   SELECT
# MAGIC     cohort_month,
# MAGIC     cohort_category,
# MAGIC     cohort_brand,
# MAGIC     COUNT(DISTINCT user_id) AS cohort_size
# MAGIC   FROM
# MAGIC     user_first_purchase_details
# MAGIC   GROUP BY
# MAGIC     cohort_month,
# MAGIC     cohort_category,
# MAGIC     cohort_brand
# MAGIC )
# MAGIC -- Select final data for the gold table
# MAGIC SELECT
# MAGIC   cs.cohort_month,
# MAGIC   cs.cohort_category,
# MAGIC   cs.cohort_brand,
# MAGIC   cs.activity_month,
# MAGIC   cs.month_number,
# MAGIC   cs.retained_users,
# MAGIC   csz.cohort_size, -- Use cohort_size from the new cohort_sizes CTE
# MAGIC   cs.total_revenue_from_cohort,
# MAGIC   cs.total_purchases_from_cohort
# MAGIC FROM
# MAGIC   cohort_summary cs
# MAGIC JOIN
# MAGIC   cohort_sizes csz
# MAGIC   ON cs.cohort_month = csz.cohort_month
# MAGIC   AND cs.cohort_category = csz.cohort_category
# MAGIC   AND cs.cohort_brand = csz.cohort_brand
# MAGIC ORDER BY
# MAGIC   cs.cohort_month,
# MAGIC   cs.cohort_category,
# MAGIC   cs.cohort_brand,
# MAGIC   cs.month_number;

# COMMAND ----------

